# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f823de32c8a306285116e267911131f1fd021fad4ecb7b69be640f251f36ba271bfbbce443640df00b4eaacdffbd21431d94948af2702e1fa6c594e5d1d75f

test:
  secret_key_base: 1da83ad928f4eb16fd3a2baae07a70666ce3ee39c3152c44832c2bc3737f2dadbcb395310c55291f4c86db441c25dde1462a598afcd3a54b2b02e62bb639af0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
